project:
  type: website

website:
  title: "Educatorial"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - NeoMapas.qmd
      - RLE-workshops.qmd
      - biodiv-workshops.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



