---
title: "Educatorial"
---

My name is José R. Ferrer-Paris, I am a senior lecturer at the Sydney campus of the University of New South Wales (UNSW Sydney).

In this website I want to share my experience in education and teaching. My education contributions have varied between my career stages, primarily due to opportunity, as I have a couple of career interruptions, and sometimes had roles focused on research or project management.

At UNSW Sydney I make significant contributions to broad education objectives. I have given **skills seminars** for Higher Degree Research students, organised **work experiences** for Year 10 High School students, and contributed to **software and data workshops** with several groups and organisations on and off campus.

At both UNSW and at the Non Government Organization Provita in Venezuela I have engaged in **capacity building and training** activities for the Red List of Ecosystem in Australia and internationally. 

Prior to appointment to my research position at UNSW, I taught **undergrad and postgrad courses** at the Venezuelan Institute of Scientific Research (IVIC). 

Here I will show a bit of my experience, resources and products related to these educational activities:

- Work experience at UNSW
- CodeRs, Stats Lunch and Hacky Hours at UNSW and Cape Town University
- Capacity building for Red List of Ecosystems around the world 
- Capacity building in Venezuela
- NeoMaps Field courses in Venezuela
