---
title: "NeoMapas: Biodiversity monitoring in Venezuela"
---

In my early career I had more education duties and always achieved a high standard. I was one of the driving forces in organising and  delivering of international courses on biodiversity monitoring in Venezuela. I was coordinator of field work and lab activities in 2006, and course convenor in 2009 and 2010. Several participants of these courses later joined the postgraduate program, completed internships or became research assistants at the Ecology Center of the Venezuelan Institute for Scientific Research. 

For international students, this experience lead to new career opportunities and renewed inspiration to do conservation science. One French participant (Antoine Escalas) wrote in 2007: 

> "I got a job much faster than I imagined, in a company that works as a consultant for the construction of dams around the world... They liked that I spent 1 year in Venezuela, that I speak Spanish, that I know a little about GIS ...It seems that my stay with you was decisive." 

One of the American participants (Janet Van Zoeren) went back to her home country to complete her undergrad studies and was inspired to apply for postgrad studies in biological conservation, she wrote in 2012:

>"Yes! I have 3 in-person interviews this month -- with all three schools I applied to. I will find out by the end of the month where I've been officially accepted, and will of course let you know what I hear at that time! It's very exciting, and I do truly appreciate your help in this endeavor. I wouldn't be here without your inspiration and assistance!".
