---
title: "uDASH Year 10 Work Experience"
subtitle: "2022 to 2024"
---
In 2022 I led UNSW Data Science Hub (uDASH) work experience program for Year 10 students, aiming at getting High School students excited about data science and considering it as a career option. We first participated in some university wide activities, organised by UNSW Future Students, including the 2022 UNSW Science Experience Day and the Explore UNSW Science Day in July 2022. Then, we started preparing for our main activity in November 2022. I led the team that designed the program of the week, with a combination of presentations from invited speakers (“meet a data scientist” sessions), morning lectures, lunch-break fun activities (campus tour, iCinema experience and Math outreach activities), guided hands-on coding work with real datasets in the afternoons, and a final presentation session for all students to share their projects and learned lessons. I was also responsible for welcoming the students, delivering the introductory lectures and coordinating all the staff involved (11 uDASH member and postdocs from Math, BEES and Psychology, two undergrad student helpers from UNSW DataSoc, PhD students from the SciX program, 9 Math Workshop and iCinema facilitators and 2 guest presenters).

The work experience week was attended by 40 Year-10 students from 12 high schools with diverse backgrounds and varying level of previous experience in coding and mathematics. Feedback was overwhelmingly positive, one of the participants wrote: 

> "The lecturers were extremely nice and caring and they implemented the feedback that we gave them every day- I was really touched by that. The content was taught in a fun and informative way, I never knew how much I would like Data Science until I came to the Work Experience." 

In 2023 I was also part of the team coordinating that year's work experience week. We updated the material and benefited greatly from the previous experience to guarantee a similar level of success.

